/* ============================================================
   REFINER DATABASE
   ------------------------------------------------------------
   Each entry is a refining "recipe":
     output:  the resulting element/material
     outQty:  units produced per cycle
     inputs:  [{ name, qty }, ...]  ingredients consumed

   Source: mmastrac/no-mans-sky-recipes (community dataset)
   ============================================================ */

const REFINER_DB = [
    { output: "Advanced Ion Battery", outQty: 1, inputs: [{ name: "Pure Ferrite", qty: 10 }, { name: "Sodium Nitrate", qty: 10 }, { name: "Silver", qty: 10 }] },
    { output: "Ammonia", outQty: 1, inputs: [{ name: "Paraffinium", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Ammonia", outQty: 1, inputs: [{ name: "Paraffinium", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Ammonia", outQty: 1, inputs: [{ name: "Fungal Mold", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Ammonia", outQty: 1, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Di-hydrogen", qty: 1 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Tritium", qty: 20 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Silver", qty: 20 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Gold", qty: 10 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Aronium", outQty: 1, inputs: [{ name: "Paraffinium", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Platinum", qty: 5 }] },
    { output: "Cactus Flesh", outQty: 1, inputs: [{ name: "Pyrite", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Cactus Flesh", outQty: 1, inputs: [{ name: "Pyrite", qty: 1 }, { name: "Sulphurine", qty: 1 }] },
    { output: "Cactus Flesh", outQty: 2, inputs: [{ name: "Pyrite", qty: 1 }, { name: "Cactus Flesh", qty: 1 }] },
    { output: "Cadmium", outQty: 2, inputs: [{ name: "Cadmium", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Fungal Mold", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Gamma Root", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Cactus Flesh", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Solanium", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Star Bulb", qty: 1 }] },
    { output: "Carbon", outQty: 1, inputs: [{ name: "Oxygen", qty: 1 }] },
    { output: "Carbon", outQty: 2, inputs: [{ name: "Condensed Carbon", qty: 1 }] },
    { output: "Carbon Crystal", outQty: 1, inputs: [{ name: "Carbon", qty: 50 }, { name: "Condensed Carbon", qty: 50 }] },
    { output: "Carbon Crystal", outQty: 1, inputs: [{ name: "Carbon", qty: 40 }, { name: "Condensed Carbon", qty: 40 }, { name: "Tritium", qty: 50 }] },
    { output: "Chloride Lattice", outQty: 1, inputs: [{ name: "Salt", qty: 50 }, { name: "Chlorine", qty: 50 }] },
    { output: "Chloride Lattice", outQty: 1, inputs: [{ name: "Salt", qty: 40 }, { name: "Chlorine", qty: 40 }, { name: "Tritium", qty: 50 }] },
    { output: "Chlorine", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Chlorine", outQty: 150, inputs: [{ name: "Chloride Lattice", qty: 1 }] },
    { output: "Chlorine", outQty: 6, inputs: [{ name: "Chlorine", qty: 1 }, { name: "Oxygen", qty: 2 }] },
    { output: "Chlorine", outQty: 1, inputs: [{ name: "Salt", qty: 2 }] },
    { output: "Chlorine", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Salt", qty: 1 }] },
    { output: "Chlorine", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Chlorine", qty: 1 }] },
    { output: "Chlorine", outQty: 5, inputs: [{ name: "Salt", qty: 2 }, { name: "Oxygen", qty: 2 }] },
    { output: "Chlorine", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 2, inputs: [{ name: "Cadmium", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 3, inputs: [{ name: "Emeril", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 1, inputs: [{ name: "Copper", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 4, inputs: [{ name: "Indium", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 4, inputs: [{ name: "Activated Cadmium", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 8, inputs: [{ name: "Activated Indium", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 6, inputs: [{ name: "Activated Emeril", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 2, inputs: [{ name: "Activated Copper", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 5, inputs: [{ name: "Silver", qty: 1 }, { name: "Gold", qty: 1 }, { name: "Copper", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 10, inputs: [{ name: "Silver", qty: 1 }, { name: "Gold", qty: 1 }, { name: "Cadmium", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 20, inputs: [{ name: "Silver", qty: 1 }, { name: "Gold", qty: 1 }, { name: "Emeril", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 30, inputs: [{ name: "Silver", qty: 1 }, { name: "Gold", qty: 1 }, { name: "Indium", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 1, inputs: [{ name: "Cadmium", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 4, inputs: [{ name: "Indium", qty: 2 }] },
    { output: "Chromatic Metal", outQty: 3, inputs: [{ name: "Emeril", qty: 2 }] },
    { output: "Chromatic Metal", outQty: 1, inputs: [{ name: "Copper", qty: 2 }] },
    { output: "Chromatic Metal", outQty: 2, inputs: [{ name: "Activated Cadmium", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 4, inputs: [{ name: "Activated Indium", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 3, inputs: [{ name: "Activated Emeril", qty: 1 }] },
    { output: "Chromatic Metal", outQty: 1, inputs: [{ name: "Activated Copper", qty: 1 }] },
    { output: "Cobalt", outQty: 2, inputs: [{ name: "Ionized Cobalt", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 1, inputs: [{ name: "Cyto-Phosphate", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 150, inputs: [{ name: "Carbon Crystal", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 1, inputs: [{ name: "Carbon", qty: 2 }] },
    { output: "Condensed Carbon", outQty: 2, inputs: [{ name: "Faecium", qty: 1 }, { name: "Carbon", qty: 2 }] },
    { output: "Condensed Carbon", outQty: 3, inputs: [{ name: "Faecium", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 2, inputs: [{ name: "Faecium", qty: 1 }, { name: "Mordite", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 2, inputs: [{ name: "Uranium", qty: 1 }, { name: "Di-hydrogen", qty: 1 }] },
    { output: "Condensed Carbon", outQty: 5, inputs: [{ name: "Carbon", qty: 2 }, { name: "Oxygen", qty: 2 }] },
    { output: "Condensed Carbon", outQty: 6, inputs: [{ name: "Condensed Carbon", qty: 1 }, { name: "Oxygen", qty: 2 }] },
    { output: "Copper", outQty: 2, inputs: [{ name: "Copper", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Destabilized Sodium", outQty: 1, inputs: [{ name: "Sodium", qty: 50 }, { name: "Sodium Nitrate", qty: 50 }] },
    { output: "Destabilized Sodium", outQty: 1, inputs: [{ name: "Sodium", qty: 40 }, { name: "Sodium Nitrate", qty: 40 }, { name: "Tritium", qty: 50 }] },
    { output: "Deuterium", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 1 }, { name: "Tritium", qty: 1 }] },
    { output: "Di-hydrogen", outQty: 50, inputs: [{ name: "Di-hydrogen Jelly", qty: 1 }] },
    { output: "Di-hydrogen", outQty: 1, inputs: [{ name: "Tritium", qty: 5 }] },
    { output: "Di-hydrogen Jelly", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 30 }] },
    { output: "Dioxite", outQty: 1, inputs: [{ name: "Carbon", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Dioxite", outQty: 2, inputs: [{ name: "Condensed Carbon", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Dioxite", outQty: 1, inputs: [{ name: "Ammonia", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Dioxite", outQty: 1, inputs: [{ name: "Ammonia", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Dioxite", outQty: 1, inputs: [{ name: "Frost Crystal", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Tritium", qty: 20 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Silver", qty: 20 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Gold", qty: 10 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Platinum", qty: 5 }] },
    { output: "Dirty Bronze", outQty: 1, inputs: [{ name: "Pyrite", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Emeril", outQty: 2, inputs: [{ name: "Emeril", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Enriched Carbon", outQty: 1, inputs: [{ name: "Radon", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Salt", qty: 10 }] },
    { output: "Enriched Carbon", outQty: 1, inputs: [{ name: "Radon", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Salt", qty: 10 }] },
    { output: "Enriched Carbon", outQty: 1, inputs: [{ name: "Radon", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Chlorine", qty: 5 }] },
    { output: "Enriched Carbon", outQty: 1, inputs: [{ name: "Radon", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Chlorine", qty: 5 }] },
    { output: "Faecium", outQty: 1, inputs: [{ name: "Mordite", qty: 3 }] },
    { output: "Faecium", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 1 }, { name: "Carbon", qty: 1 }] },
    { output: "Faecium", outQty: 1, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Nitrogen", qty: 1 }] },
    { output: "Faecium", outQty: 3, inputs: [{ name: "Faecium", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Faecium", outQty: 3, inputs: [{ name: "Carbon", qty: 2 }, { name: "Mordite", qty: 1 }] },
    { output: "Faecium", outQty: 4, inputs: [{ name: "Condensed Carbon", qty: 1 }, { name: "Mordite", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Paraffinium", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Pyrite", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Ammonia", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Uranium", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Dioxite", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 1, inputs: [{ name: "Phosphorus", qty: 1 }] },
    { output: "Ferrite Dust", outQty: 2, inputs: [{ name: "Rusted Metal", qty: 1 }] },
    { output: "Frost Crystal", outQty: 1, inputs: [{ name: "Dioxite", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Frost Crystal", outQty: 1, inputs: [{ name: "Dioxite", qty: 1 }, { name: "Radon", qty: 1 }] },
    { output: "Frost Crystal", outQty: 2, inputs: [{ name: "Dioxite", qty: 1 }, { name: "Frost Crystal", qty: 1 }] },
    { output: "Fungal Mold", outQty: 1, inputs: [{ name: "Ammonia", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Fungal Mold", outQty: 1, inputs: [{ name: "Ammonia", qty: 1 }, { name: "Nitrogen", qty: 1 }] },
    { output: "Fungal Mold", outQty: 2, inputs: [{ name: "Ammonia", qty: 1 }, { name: "Fungal Mold", qty: 1 }] },
    { output: "Gamma Root", outQty: 1, inputs: [{ name: "Uranium", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Gamma Root", outQty: 1, inputs: [{ name: "Uranium", qty: 1 }, { name: "Radon", qty: 1 }] },
    { output: "Gamma Root", outQty: 2, inputs: [{ name: "Uranium", qty: 1 }, { name: "Gamma Root", qty: 1 }] },
    { output: "Glass", outQty: 1, inputs: [{ name: "Frost Crystal", qty: 40 }] },
    { output: "Glass", outQty: 1, inputs: [{ name: "Cyto-Phosphate", qty: 50 }, { name: "Salt", qty: 50 }] },
    { output: "Glass", outQty: 1, inputs: [{ name: "Silicate Powder", qty: 40 }] },
    { output: "Gold", outQty: 1, inputs: [{ name: "Hexite", qty: 1 }] },
    { output: "Gold", outQty: 1, inputs: [{ name: "Faecium", qty: 1 }, { name: "Residual Goop", qty: 1 }] },
    { output: "Gold", outQty: 100, inputs: [{ name: "Living Pearl", qty: 1 }] },
    { output: "Gold", outQty: 10, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Oxygen", qty: 1 }, { name: "Emeril", qty: 1 }] },
    { output: "Gold", outQty: 125, inputs: [{ name: "Lemmium", qty: 1 }] },
    { output: "Gold", outQty: 125, inputs: [{ name: "Magno-Gold", qty: 1 }] },
    { output: "Gold", outQty: 125, inputs: [{ name: "Grantine", qty: 1 }] },
    { output: "Gold", outQty: 1, inputs: [{ name: "Mordite", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Gold", outQty: 2, inputs: [{ name: "Faecium", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Tritium", qty: 20 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Silver", qty: 20 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Gold", qty: 10 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Grantine", outQty: 1, inputs: [{ name: "Dioxite", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Platinum", qty: 5 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Tritium", qty: 20 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Silver", qty: 20 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Gold", qty: 10 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Herox", outQty: 1, inputs: [{ name: "Ammonia", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Platinum", qty: 5 }] },
    { output: "Indium", outQty: 2, inputs: [{ name: "Indium", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Ion Battery", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 10 }, { name: "Silver", qty: 10 }, { name: "Sodium", qty: 10 }] },
    { output: "Ionized Cobalt", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Ionized Cobalt", outQty: 150, inputs: [{ name: "TetraCobalt", qty: 1 }] },
    { output: "Ionized Cobalt", outQty: 5, inputs: [{ name: "Cobalt", qty: 2 }, { name: "Oxygen", qty: 2 }] },
    { output: "Ionized Cobalt", outQty: 6, inputs: [{ name: "Ionized Cobalt", qty: 1 }, { name: "Oxygen", qty: 2 }] },
    { output: "Ionized Cobalt", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Cobalt", qty: 1 }] },
    { output: "Ionized Cobalt", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Ionized Cobalt", qty: 1 }] },
    { output: "Ionized Cobalt", outQty: 1, inputs: [{ name: "Cobalt", qty: 2 }] },
    { output: "Ionized Cobalt", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Kelp Sac", outQty: 1, inputs: [{ name: "Salt", qty: 1 }, { name: "Nitrogen", qty: 1 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Tritium", qty: 20 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Silver", qty: 20 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Gold", qty: 10 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Ferrite Dust", qty: 120 }, { name: "Platinum", qty: 5 }] },
    { output: "Lemmium", outQty: 1, inputs: [{ name: "Uranium", qty: 30 }, { name: "Pure Ferrite", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Life Support Gel", outQty: 1, inputs: [{ name: "Oxygen", qty: 10 }, { name: "Condensed Carbon", qty: 10 }, { name: "Di-hydrogen", qty: 10 }] },
    { output: "Living Slime", outQty: 50, inputs: [{ name: "Hypnotic Eye", qty: 1 }] },
    { output: "Living Slime", outQty: 1, inputs: [{ name: "Viscous Fluids", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Carbon", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 2, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 2, inputs: [{ name: "Pure Ferrite", qty: 1 }, { name: "Carbon", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 3, inputs: [{ name: "Pure Ferrite", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 5, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Pure Ferrite", qty: 1 }, { name: "Silver", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 8, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Pure Ferrite", qty: 1 }, { name: "Gold", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 12, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Pure Ferrite", qty: 1 }, { name: "Platinum", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 1, inputs: [{ name: "Pure Ferrite", qty: 2 }] },
    { output: "Magnetized Ferrite", outQty: 3, inputs: [{ name: "Pure Ferrite", qty: 2 }, { name: "Pugneum", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 4, inputs: [{ name: "Magnetized Ferrite", qty: 3 }, { name: "Pugneum", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 10, inputs: [{ name: "Platinum", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 4, inputs: [{ name: "Indium", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 2, inputs: [{ name: "Cadmium", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 3, inputs: [{ name: "Emeril", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 1, inputs: [{ name: "Copper", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 4, inputs: [{ name: "Activated Cadmium", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 8, inputs: [{ name: "Activated Indium", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 6, inputs: [{ name: "Activated Emeril", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magnetized Ferrite", outQty: 2, inputs: [{ name: "Activated Copper", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Tritium", qty: 20 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Tritium", qty: 20 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Silver", qty: 20 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Silver", qty: 20 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Gold", qty: 10 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Gold", qty: 10 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Cobalt", qty: 60 }, { name: "Platinum", qty: 5 }] },
    { output: "Magno-Gold", outQty: 1, inputs: [{ name: "Phosphorus", qty: 30 }, { name: "Ionized Cobalt", qty: 30 }, { name: "Platinum", qty: 5 }] },
    { output: "Marrow Bulb", outQty: 1, inputs: [{ name: "Cobalt", qty: 1 }, { name: "Nitrogen", qty: 1 }] },
    { output: "Marrow Bulb", outQty: 3, inputs: [{ name: "Sodium", qty: 2 }, { name: "Mordite", qty: 1 }] },
    { output: "Marrow Bulb", outQty: 4, inputs: [{ name: "Sodium Nitrate", qty: 1 }, { name: "Mordite", qty: 1 }] },
    { output: "Mordite", outQty: 1, inputs: [{ name: "Carbon", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Mordite", outQty: 2, inputs: [{ name: "Condensed Carbon", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Mordite", outQty: 2, inputs: [{ name: "Faecium", qty: 3 }] },
    { output: "Mordite", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Nanite Cluster", outQty: 1, inputs: [{ name: "Faecium", qty: 1 }, { name: "Hexite", qty: 1 }] },
    { output: "Nanite Cluster", outQty: 50, inputs: [{ name: "Hadal Core", qty: 1 }] },
    { output: "Nanite Cluster", outQty: 15, inputs: [{ name: "Salvaged Data", qty: 1 }] },
    { output: "Nanite Cluster", outQty: 50, inputs: [{ name: "Larval Core", qty: 1 }] },
    { output: "Nanite Cluster", outQty: 1, inputs: [{ name: "Pugneum", qty: 25 }] },
    { output: "Nanite Cluster", outQty: 1, inputs: [{ name: "Platinum", qty: 35 }] },
    { output: "Nanite Cluster", outQty: 1, inputs: [{ name: "Runaway Mold", qty: 5 }] },
    { output: "Nanite Cluster", outQty: 1, inputs: [{ name: "Silver", qty: 15 }, { name: "Gold", qty: 15 }, { name: "Platinum", qty: 25 }] },
    { output: "Nitrogen", outQty: 1, inputs: [{ name: "Radon", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Nitrogen", outQty: 1, inputs: [{ name: "Radon", qty: 3 }] },
    { output: "Nitrogen", outQty: 1, inputs: [{ name: "Radon", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Nitrogen Salt", outQty: 1, inputs: [{ name: "Nitrogen", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Salt", qty: 10 }] },
    { output: "Nitrogen Salt", outQty: 1, inputs: [{ name: "Nitrogen", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Salt", qty: 10 }] },
    { output: "Nitrogen Salt", outQty: 1, inputs: [{ name: "Nitrogen", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Chlorine", qty: 5 }] },
    { output: "Nitrogen Salt", outQty: 1, inputs: [{ name: "Nitrogen", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Chlorine", qty: 5 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Fungal Mold", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Frost Crystal", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Cactus Flesh", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Solanium", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Gamma Root", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 10, inputs: [{ name: "Star Bulb", qty: 1 }, { name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 1, inputs: [{ name: "Kelp Sac", qty: 1 }] },
    { output: "Oxygen", outQty: 150, inputs: [{ name: "Superoxide Crystal", qty: 1 }] },
    { output: "Oxygen", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Carbon", qty: 1 }] },
    { output: "Oxygen", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Paraffinium", outQty: 1, inputs: [{ name: "Pyrite", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Paraffinium", outQty: 1, inputs: [{ name: "Pyrite", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Paraffinium", outQty: 1, inputs: [{ name: "Star Bulb", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Paraffinium", outQty: 1, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Paraffinium", outQty: 2, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Paraffinium", outQty: 3, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Magnetized Ferrite", qty: 1 }] },
    { output: "Paraffinium", outQty: 2, inputs: [{ name: "Silver", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Phosphorus", outQty: 1, inputs: [{ name: "Dioxite", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Phosphorus", outQty: 1, inputs: [{ name: "Dioxite", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Phosphorus", outQty: 1, inputs: [{ name: "Solanium", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Platinum", outQty: 10, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Oxygen", qty: 1 }, { name: "Chromatic Metal", qty: 250 }] },
    { output: "Platinum", outQty: 250, inputs: [{ name: "Geodesite", qty: 1 }] },
    { output: "Platinum", outQty: 250, inputs: [{ name: "Iridesite", qty: 1 }] },
    { output: "Platinum", outQty: 1, inputs: [{ name: "Gold", qty: 1 }, { name: "Silver", qty: 1 }] },
    { output: "Pure Ferrite", outQty: 2, inputs: [{ name: "Magnetized Ferrite", qty: 1 }] },
    { output: "Pure Ferrite", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 1 }] },
    { output: "Pure Ferrite", outQty: 3, inputs: [{ name: "Ferrite Dust", qty: 2 }, { name: "Pugneum", qty: 1 }] },
    { output: "Pure Ferrite", outQty: 150, inputs: [{ name: "Rare Metal Element", qty: 1 }] },
    { output: "Pyrite", outQty: 1, inputs: [{ name: "Uranium", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Pyrite", outQty: 1, inputs: [{ name: "Uranium", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Pyrite", outQty: 1, inputs: [{ name: "Cactus Flesh", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Pyrite", outQty: 1, inputs: [{ name: "Gold", qty: 1 }] },
    { output: "Pyrite", outQty: 2, inputs: [{ name: "Gold", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Radon", outQty: 1, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Radon", outQty: 1, inputs: [{ name: "Sulphurine", qty: 3 }] },
    { output: "Radon", outQty: 1, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Rare Metal Element", outQty: 1, inputs: [{ name: "Magnetized Ferrite", qty: 25 }, { name: "Oxygen", qty: 50 }] },
    { output: "Rare Metal Element", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 35 }, { name: "Pure Ferrite", qty: 35 }, { name: "Magnetized Ferrite", qty: 35 }] },
    { output: "Rare Metal Element", outQty: 1, inputs: [{ name: "Oxygen", qty: 20 }, { name: "Magnetized Ferrite", qty: 20 }, { name: "Tritium", qty: 25 }] },
    { output: "Runaway Mold", outQty: 1, inputs: [{ name: "Living Slime", qty: 1 }] },
    { output: "Rusted Metal", outQty: 2, inputs: [{ name: "Pure Ferrite", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Rusted Metal", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Salt", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Salt", outQty: 2, inputs: [{ name: "Chlorine", qty: 1 }] },
    { output: "Silver", outQty: 250, inputs: [{ name: "Aronium", qty: 1 }] },
    { output: "Silver", outQty: 250, inputs: [{ name: "Dirty Bronze", qty: 1 }] },
    { output: "Silver", outQty: 250, inputs: [{ name: "Herox", qty: 1 }] },
    { output: "Sodium", outQty: 1, inputs: [{ name: "Marrow Bulb", qty: 1 }] },
    { output: "Sodium", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Carbon", qty: 1 }] },
    { output: "Sodium", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Condensed Carbon", qty: 1 }] },
    { output: "Sodium", outQty: 2, inputs: [{ name: "Sodium Nitrate", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Carbon", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Condensed Carbon", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Faecium", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Faecium", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 3, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Magnetized Ferrite", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Marrow Bulb", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Kelp Sac", qty: 1 }, { name: "Sodium Nitrate", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Sodium", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 2, inputs: [{ name: "Sodium Nitrate", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Sodium", qty: 2 }] },
    { output: "Sodium Nitrate", outQty: 1, inputs: [{ name: "Sodium", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 3, inputs: [{ name: "Sodium Nitrate", qty: 1 }, { name: "Pugneum", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 150, inputs: [{ name: "Destabilized Sodium", qty: 1 }] },
    { output: "Sodium Nitrate", outQty: 50, inputs: [{ name: "Crystal Sulphide", qty: 1 }] },
    { output: "Solanium", outQty: 1, inputs: [{ name: "Phosphorus", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Solanium", outQty: 1, inputs: [{ name: "Phosphorus", qty: 1 }, { name: "Sulphurine", qty: 1 }] },
    { output: "Solanium", outQty: 2, inputs: [{ name: "Phosphorus", qty: 1 }, { name: "Solanium", qty: 1 }] },
    { output: "Solanium", outQty: 1, inputs: [{ name: "Sulphurine", qty: 1 }, { name: "Di-hydrogen", qty: 1 }] },
    { output: "Star Bulb", outQty: 1, inputs: [{ name: "Paraffinium", qty: 2 }, { name: "Oxygen", qty: 1 }] },
    { output: "Star Bulb", outQty: 1, inputs: [{ name: "Paraffinium", qty: 1 }, { name: "Nitrogen", qty: 1 }] },
    { output: "Star Bulb", outQty: 2, inputs: [{ name: "Paraffinium", qty: 1 }, { name: "Star Bulb", qty: 1 }] },
    { output: "Starship Launch Fuel", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 10 }, { name: "Ferrite Dust", qty: 20 }, { name: "Sodium Nitrate", qty: 5 }] },
    { output: "Starship Launch Fuel", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 10 }, { name: "Pure Ferrite", qty: 20 }, { name: "Sodium", qty: 10 }] },
    { output: "Starship Launch Fuel", outQty: 1, inputs: [{ name: "Di-hydrogen", qty: 10 }, { name: "Magnetized Ferrite", qty: 10 }, { name: "Sodium Nitrate", qty: 5 }] },
    { output: "Sulphurine", outQty: 1, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Chromatic Metal", qty: 1 }] },
    { output: "Sulphurine", outQty: 1, inputs: [{ name: "Nitrogen", qty: 3 }] },
    { output: "Sulphurine", outQty: 1, inputs: [{ name: "Nitrogen", qty: 1 }, { name: "Oxygen", qty: 1 }] },
    { output: "Superoxide Crystal", outQty: 1, inputs: [{ name: "Oxygen", qty: 100 }, { name: "Tritium", qty: 50 }] },
    { output: "Superoxide Crystal", outQty: 1, inputs: [{ name: "Oxygen", qty: 40 }, { name: "Uranium", qty: 40 }, { name: "Tritium", qty: 50 }] },
    { output: "TetraCobalt", outQty: 1, inputs: [{ name: "Cobalt", qty: 50 }, { name: "Ionized Cobalt", qty: 50 }] },
    { output: "TetraCobalt", outQty: 1, inputs: [{ name: "Cobalt", qty: 40 }, { name: "Ionized Cobalt", qty: 40 }, { name: "Tritium", qty: 50 }] },
    { output: "Thermic Condensate", outQty: 1, inputs: [{ name: "Sulphurine", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Salt", qty: 10 }] },
    { output: "Thermic Condensate", outQty: 1, inputs: [{ name: "Sulphurine", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Salt", qty: 10 }] },
    { output: "Thermic Condensate", outQty: 1, inputs: [{ name: "Sulphurine", qty: 100 }, { name: "Carbon", qty: 20 }, { name: "Chlorine", qty: 5 }] },
    { output: "Thermic Condensate", outQty: 1, inputs: [{ name: "Sulphurine", qty: 100 }, { name: "Condensed Carbon", qty: 10 }, { name: "Chlorine", qty: 5 }] },
    { output: "Unstable Plasma", outQty: 1, inputs: [{ name: "Oxygen", qty: 10 }, { name: "Ferrite Dust", qty: 20 }, { name: "Carbon", qty: 20 }] },
    { output: "Unstable Plasma", outQty: 1, inputs: [{ name: "Oxygen", qty: 10 }, { name: "Ferrite Dust", qty: 20 }, { name: "Condensed Carbon", qty: 10 }] },
    { output: "Unstable Plasma", outQty: 1, inputs: [{ name: "Oxygen", qty: 10 }, { name: "Pure Ferrite", qty: 20 }, { name: "Carbon", qty: 20 }] },
    { output: "Unstable Plasma", outQty: 1, inputs: [{ name: "Oxygen", qty: 10 }, { name: "Condensed Carbon", qty: 10 }, { name: "Pure Ferrite", qty: 20 }] },
    { output: "Uranium", outQty: 1, inputs: [{ name: "Radon", qty: 1 }, { name: "Di-hydrogen", qty: 1 }] },
    { output: "Uranium", outQty: 1, inputs: [{ name: "Phosphorus", qty: 2 }, { name: "Ferrite Dust", qty: 1 }] },
    { output: "Uranium", outQty: 1, inputs: [{ name: "Phosphorus", qty: 2 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Uranium", outQty: 1, inputs: [{ name: "Gamma Root", qty: 2 }, { name: "Salt", qty: 1 }] },
    { output: "Uranium", outQty: 1, inputs: [{ name: "Ferrite Dust", qty: 1 }, { name: "Radon", qty: 1 }] },
    { output: "Uranium", outQty: 2, inputs: [{ name: "Radon", qty: 1 }, { name: "Pure Ferrite", qty: 1 }] },
    { output: "Uranium", outQty: 3, inputs: [{ name: "Radon", qty: 1 }, { name: "Magnetized Ferrite", qty: 1 }] },
    { output: "Viscous Fluids", outQty: 1, inputs: [{ name: "Residual Goop", qty: 1 }] },
    { output: "Warp Cell", outQty: 1, inputs: [{ name: "Condensed Carbon", qty: 25 }, { name: "Sodium", qty: 10 }, { name: "Chromatic Metal", qty: 250 }] },
    { output: "Warp Cell", outQty: 1, inputs: [{ name: "Carbon", qty: 50 }, { name: "Sodium Nitrate", qty: 5 }, { name: "Chromatic Metal", qty: 250 }] },
    { output: "Warp Cell", outQty: 1, inputs: [{ name: "Condensed Carbon", qty: 25 }, { name: "Sodium Nitrate", qty: 5 }, { name: "Chromatic Metal", qty: 250 }] }
];
